global:
  scrape_interval: 15s
scrape_configs:
  - job_name: ddns-runner
    metrics_path: /internal/status/prometheus
    static_configs:
      - targets: [ddns-runner:3000]
  - job_name: phd-website-analytics-server
    metrics_path: /internal/status/prometheus
    static_configs:
      - targets: [phd-website-analytics-server:8080]
