web:
  cors:
    allowed_origins:
      - mapping: '/api/v1/analytics/**'
        origin: 'https://prac.im.pwr.edu.pl/'
      - mapping: '/api/v1/analytics/**'
        origin: 'https://m1loseph.github.io/'
