spring:
  data:
    mongodb:
      uri: mongodb://test:test@localhost:27017/analytics-server-db?authSource=admin

web:
  limiting:
    redis_url: redis://localhost:6379
  cors:
    mapping: '/**'
    allowed_origins:
      - '*'
