apiVersion: 1
prune: true
datasources:
  - name: Prometheus
    type: prometheus
    # TODO: check difference between proxy and direct
    access: proxy
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST