version: "3.8"
services: 
  nginx:
    image: nginx:1.25.4-bookworm
    restart: always
    ports:
      - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./fullchain.pem:/etc/nginx/fullchain.pem"
      - "./privkey.pem:/etc/nginx/privkey.pem"
    depends_on:
      - phd-website-analytics-server
  mongo:
    image: mongo:4.4.18
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "/mnt/kingspec-usb/phd-website-analytics-server/mongodb:/data/db"
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
  redis:
    image: redis:7.2.4
    restart: always
    ports:
      - "6379:6379"
  phd-website-analytics-server:
    image: m1loseph/phd-website-analytics-server:0.0.1
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATA_MONGODB_URI: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongo:27017/${MONGODB_DATABASE_NAME}?authSource=admin
      WEB_LIMITING_REDIS_URL: redis://redis:6379
  ddns-runner:
    image: m1loseph/ddns-runner:0.0.1
    restart: always
    ports:
      - "3000:3000"
    environment:
      DDNS_RUNNER_DOMAIN: phdwebsite
      DDNS_RUNNER_TOKEN: 308098ad-b4e4-46b4-a88e-ec6862c016b6
      DDNS_RUNNER_SERVER_PORT: 3000
      RUST_LOG: trace
    volumes:
      - "/etc/ssl:/etc/ssl"
  prometheus:
    image: prom/prometheus:v2.50.1
    user: root
    restart: always
    ports:
      - "9090:9090"
    depends_on:
      - ddns-runner
      - phd-website-analytics-server
    volumes:
      - "/home/pi/prometheus:/prometheus"
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"

