name: Continuous Integration
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.1

      - name: Install flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: "3.16.7"
          channel: stable

      - name: Run build script
        working-directory: phd-website
        run: ./scripts/ci/build.sh ${{ secrets.DEPLOYMENT_ENDPOINT }}

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build-artifact
          path: phd-website/build/web
          retention-days: 1
