name: Continuous Integration
on:
  pull_request:
    branches: [master]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.1

      - name: Install flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: "3.16.4"
          channel: "stable"

      - name: Install dependencies
        working-directory: phd_website
        run: flutter pub get

      - name: Run tests
        working-directory: phd_website
        run: flutter test

      - name: Build web app
        working-directory: phd_website
        run: flutter build web
