name: DDNS-Runner Deployment
on:
  push:
    tags:
      - "ddns-runner/*"
jobs:
  test:
    outputs: 
      ddns-version: ${{ steps.determine_version.outputs.version }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run tests
        working-directory: backend/ddns-runner/ddns-runner
        run: cargo test

      - name: Determine version
        id: determine_version
        working-directory: backend/ddns-runner/ddns-runner
        run: echo "version=$(./tools/current-version.sh)" >> "$GITHUB_OUTPUT"

  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        env:
          DDNS_VERSION: ${{ needs.test.outputs.ddns-version.version }}
        with:
          context: backend/ddns-runner/ddns-runner
          platforms: linux/amd64,linux/arm64
          push: true
          tags: m1loseph/ddns-runner:${{}}
