name: Continuous Integration
on:
  pull_request:
    branches: [master]
    paths: 
      - 'phd_website/**'
  push:
    branches: [master]
    paths: 
      - 'phd_website/**'
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"
          channel: stable

      - name: Run build script
        working-directory: phd_website
        run: ./scripts/ci/build.sh ${{ secrets.DEPLOYMENT_ENDPOINT }} https://phdwebsite.duckdns.org pwr_server

      - name: Save artifact
        if: ${{ startsWith(github.ref, 'refs/tags/phdwebsite/') }}
        uses: actions/upload-artifact@v4
        with:
          name: web-build-artifact
          path: phd_website/build/web
          retention-days: 1
