name: Recover secrets
on:
  workflow_dispatch:
jobs:
  encrypt-and-print:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Encrypt and print
        env:
          RECOVERY_OPENSSL_PUBLIC_KEY: ${{ secrets.RECOVERY_OPENSSL_PUBLIC_KEY }}
          VPN_USER: ${{ secrets.VPN_USER }}
          VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}
          VPN_GATEWAY: ${{ secrets.VPN_GATEWAY }}
        run: |
          set -e
          echo "${RECOVERY_OPENSSL_PUBLIC_KEY}" > public.pem
          SECRETS=("VPN_USER|${VPN_USER}" "VPN_PASSWORD|${VPN_PASSWORD}" "VPN_GATEWAY|${VPN_GATEWAY}")
          for SECRET in ${SECRETS[@]}
          do
            SECRET_NAME=$(echo "${SECRET}" | cut -d "|" -f 1)
            SECRET_VALUE=$(echo "${SECRET}" | cut -d "|" -f 2)

            OUTPUT="${SECRET_NAME}.bin"

            echo "${SECRET_VALUE}" | openssl pkeyutl -encrypt -pubin -inkey public.pem -out "${OUTPUT}"
            ENCYPTED_VALUE=$(cat "${OUTPUT}" | base64)
            echo "${SECRET_NAME}=${ENCYPTED_VALUE}"
          done

          